### ISSUE TITLE
The generic List implementation leaks

### ISSUE THREAD

**Issue by anacrolix** [fufuok/utils#1]
Removing the Front and Back Node from the generic List implementation can leave Front and Back set to non-nil values. I suspect there are more specific issues if I dig in. I thought it would be helpful to point out there might be issues before trying to fix them myself for now.

Thanks for the module!

**Comment by fufuok** [comment]
Thanks, I'll follow up later.

**Comment by anacrolix** [comment]
I created https://pkg.go.dev/github.com/anacrolix/generics@v0.0.0-20230314234802-b3aec36ef63e/list to make the features I depended on available again.

**Comment by fufuok** [comment]
This package is from https://github.com/zyedidia/generic, maybe you can pr.
