### ISSUE TITLE
Is this lib a collection of other go libs?

### ISSUE THREAD

**Issue by thecodeworks** [fufuok/utils#2]
Is this lib a collection of other go libs? if so, what's the meaning of doing this?

**Comment by fufuok** [comment]
Most of them are helper functions accumulated in the project, such as all go files in the root directory, myip, ntp, pools, assert, etc. 

There are indeed several third-party libraries integrated in it, they are the most commonly used basic libraries that are unlikely to have major updates during project development. 

These third-party libraries to some extent add customized functions (without altering the original library code) required by their own projects, such as xjson, xsync, xid. 

The advantage is that the maintenance workload is reduced, and all projects in use will not be affected by new features updates of the third-party libraries, such as generics or unstable versions. 

Of course, the golang exp related libraries in the generic directory are of little significance, and are kept for future addition of new functions.
